name: farm-manager-backend

services:
  pg:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=farm-manager
      - TZ=America/Sao_Paulo
    volumes:
      - farm-manager-pg-data:/var/lib/postgresql/data
    networks:
      - observability

volumes:
  farm-manager-pg-data:
    driver: local

networks:
  observability:
    external: true
